### ISSUE TITLE
IIP path should be same as digipal path by default

### ISSUE THREAD

**Issue by pastokes** [kcl-ddh/digipal#17]
By default, the path for the IIP server should be assumed to be the same as that for the main DigiPal framework. This should then be overridden either through the admin interface or local_settings.py. This would then make the virtual machine much easier for people to use.

**Comment by geoffroy-noel-ddh** [comment]
That's now fixed in v1.2.2b on DockerHub. Both Django and IIPSrv are served through the webserver. Only web path varies.
