### ISSUE TITLE
Docker Image - Externalise the Database

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [kcl-ddh/digipal#20]
Mount the local drive and save the database on that mount so we can persist the data across framework instances. It would help with:
- making the system easier to copy across machines
- backup of the data
- upgrading the framework without losing data

**Comment by pastokes** [comment]
As an intermediate stage, I wonder if integrating something like this could be helpful: https://github.com/django-dbbackup/django-dbbackup
I guess it wouldn't back up the images, but at least it should catch everything else, correct?

**Comment by goffer-looney** [comment]
Fixed as part of version 2.1.0 soon to be released on Dockerhub. See upgrade info on Dockerhub for more details:
https://hub.docker.com/r/gnoelddh/archetype/

**Comment by geoffroy-noel-ddh** [comment]
Externalisation of data implemented as part of version 2.1.0 soon to be released on Dockerhub. See upgrade info on Dockerhub for more details:
https://hub.docker.com/r/gnoelddh/archetype/
