### ISSUE TITLE
Record_hands.html template throws UnicodeDecode Error for any non-ASCII character in the ItemPart label.

### ISSUE THREAD

**Issue by pastokes** [kcl-ddh/digipal#31]
The record_hands.html template assumes that all characters in the ItemPart label are ASCII and so it throws a UnicodeDecodeError if not ('ascii' codec can't decode byte XXX in position YYY: ordinal not in range(128)). This is evident particularly in DigiPal as many Item Parts have en-dashes in the labels and so all associated Hand pages do not display. See, for instance, most of the hands at https://www.digipal.eu/digipal/scribes/1/hands/

I imagine the same problem exists elsewhere so we probably need to do a careful search at some point, but this is the only one I've found so far.

**Comment by geoffroy-noel-ddh** [comment]
Thanks for reporting that Peter. Presumably the bug shouldn't be too difficult to fix, hopefully I'll be able to look into that relatively soon.

**Comment by geoffroy-noel-ddh** [comment]
Fixed in commit e6629af9d6e2d9c7b599b0b54a7b3012c6dc73d5 (develop branch, will be part of next release: 2.3.0)
