### ISSUE TITLE
transcription interface

### ISSUE THREAD

**Issue by kabikaj** [kcl-ddh/digipal#50]
Hi again! I tried to look for some documentation or tutorials for the transcription part, but was unable to find anything. Is there any links containing some explanations? I failed to unerstand it by mysel by playing with it. I am very interested in all the annotation options and in the synchronisation with the image. Thanks!

**Comment by pastokes** [comment]
The documentation needs much more work, and again volunteers are welcome! For the transcription, agreed there isn't much yet. There's a little in the wiki at [Linking Image Regions with Text Regions](https://github.com/kcl-ddh/digipal/wiki/Linking-image-regions-with-text-regions), as well as [Text Editor (customisations)](https://github.com/kcl-ddh/digipal/wiki/Text-Editor-(customisations)) and the [Text Model](https://github.com/kcl-ddh/digipal/wiki/Text-Model-%5BDRAFT%5D), but they all assume you already have a text in place. In the meantime there's a PDF with some screenshots to help show the process in the docs folder, [Introduction to Archetype.pdf](https://github.com/kcl-ddh/digipal/blob/master/digipal/doc/Introduction%20to%20Archetype.pdf). The transcription interface is towards the middle.

**Comment by pastokes** [comment]
I'm assuming this answered the question and so I'm closing the issue.
