### ISSUE TITLE
What is the initial username and password of the admin

### ISSUE THREAD

**Issue by HugoChevroton** [kcl-ddh/digipal#58]
Hey,

I'm installing Archetype from the github source (https://github.com/kcl-ddh/digipal/)
The site is running, but what is the initial super user name and password? (http://localhost:8000/admin/login/)

Regards,
Hugo

**Comment by pastokes** [comment]
Normally the default login and password for the admin interface are _admin_ and _admin_ respectively (obviously this should be changed immediately after installation!).

You can also create a new account and/or change the password from the command line via Django by using `python manage.py changepassword` and `python manage.py createsuperuser` (running manage.py from the top-level digipal directory). For more details try the built-in help (e.g. `python manage.py help createsuperuser`) or [the Django documentation](https://docs.djangoproject.com/en/1.8/ref/django-admin/).

**Comment by HugoChevroton** [comment]
Thank you for this answer.
The default login admin doesn't work, but I done the change with manage.py createsuperuser.

Regards,
