### ISSUE TITLE
pink rectangle(s) next to image in paleographical editor

### ISSUE THREAD

**Issue by kabikaj** [kcl-ddh/digipal#72]
I uploaded several jpg images of around 2.2 MB each and all al them are being displayed together with one or more duplicates of the image as pink rectangles in the paleographic editor. I also tried to resize the images to 50% or 25% of their size, but the visualization is the same. Is there anything I could do to solve this problem? Thanks!

**Comment by pastokes** [comment]
Thanks for reporting this. To be clear, you see the full image, but _also_ see pink rectangles and/or the same image repeated in the same viewer window? So it's not the same as Issue #51, although it may well be related? If you could upload a screenshot then that would be helpful. In any case, I've never seen that before, so I can't really help except to suggest continuing to try different formats and resolutions as you have been.

**Comment by geoffroy-noel-ddh** [comment]
Hi @kabikaj , this is a known issue we've had for a while although we don't really know where the problem originate. As you've mentioned it tends to occur with lower resolution images. One possible work-around consists in increasing the size of the image (by 25%-50%) before re-uploading it, this usually works. What are the dimensions?

**Comment by kabikaj** [comment]
The image I am testing is 3474x4098 pixels. The weird thing is that the image is bigger than others that work well, so not specially small. I just also tried to convert it to png and uplaod it. It had no effect.

**Comment by geoffroy-noel-ddh** [comment]
Could you share the image here, or somewhere else temporarily? If not you can email me at geoffroy dot noel (kcl.ac.uk). I'll see if I can reproduce. Which version of Archetype do you use?

**Comment by kabikaj** [comment]
Thank you very much for checking it! I made an image of the current state of our archetype. I send you now the link by email. We are still using Archetype 2.3.1. We were planning to upgrade but haven't done it yet.

**Comment by geoffroy-noel-ddh** [comment]
Closing this issue as you've reported that the pink tiles have disappeared with the latest version of Archetype (2.7). We can reopen if you see them reappear.
